# Customer life time value prediction

The objective of the project is to predict the CLTV based on the information collected from an IBM  customer database. The purpose of the project is to show how a company can  reduce its marketing cost by focusing on the most valuable customers.

In [34]:
import pandas as pd
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
#we took the data from https://community.ibm.com/accelerators/?context=analytics&query=tel&type=Data
#we have three dataframe: Telco_customer_churn_demographics,Telco_customer_churn,Telco_customer_churn_services)
#we need to merge them.

In [4]:
# Import the datafram on the customer demographics 

dfd = pd.read_excel('Telco_customer_churn_demographics.xlsx')

In [5]:
# Import the datafram on the customer churn

dfc = pd.read_excel('Telco_customer_churn.xlsx')

In [6]:
# Import the datafram on the customer churn services 

dfs = pd.read_excel('Telco_customer_churn_services.xlsx')

In [18]:
dfs = dfs.rename(columns={'Customer ID':'CustomerID'})

In [20]:
# Merge the dataframe of the customer churn with the dataframe of the the customer churn services 

dfcs = pd.merge(left=dfc, right=dfs, left_on='CustomerID', right_on='CustomerID')

In [24]:
# Merge the previous dataframe merged with the dataframe of the the customer demographics 

df = pd.merge(left=dfcs, right=dfd, left_on='CustomerID', right_on='Customer ID')

In [31]:
df.shape

(7043, 71)

In [33]:
df.describe()

,Count_x,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV,Count_y,...,Avg Monthly GB Download,Monthly Charge,Total Charges_y,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Count,Age,Number of Dependents
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.0,...,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.0,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755,1.0,...,20.515405,64.761692,2280.381264,1.962182,6.860713,749.099262,3034.379056,1.0,46.509726,0.468692
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152,0.0,...,20.418940,30.090047,2266.220462,7.902614,25.104978,846.660055,2865.204542,0.0,16.750352,0.962802
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000,1.0,...,0.000000,18.250000,18.800000,0.000000,0.000000,0.000000,21.360000,1.0,19.000000,0.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000,1.0,...,3.000000,35.500000,400.150000,0.000000,0.000000,70.545000,605.610000,1.0,32.000000,0.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000,1.0,...,17.000000,70.350000,1394.550000,0.000000,0.000000,401.440000,2108.640000,1.0,46.000000,0.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000,1.0,...,27.000000,89.850000,3786.600000,0.000000,0.000000,1191.100000,4801.145000,1.0,60.000000,0.000000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000,1.0,...,85.000000,118.750000,8684.800000,49.790000,150.000000,3564.720000,11979.340000,1.0,80.000000,9.000000

In [35]:
df.head(3)

,CustomerID,Count_x,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender_x,...,Total Revenue,Customer ID,Count,Gender_y,Age,Under 30,Senior Citizen_y,Married,Dependents_y,Number of Dependents
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,129.09,3668-QPYBK,1,Male,37,No,No,No,No,0
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,169.89,9237-HQITU,1,Female,19,Yes,No,No,Yes,2
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,917.70,9305-CDSKC,1,Female,31,No,No,No,Yes,2

In [36]:
df.columns

Index(['CustomerID', 'Count_x', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender_x', 'Senior Citizen_x',
       'Partner', 'Dependents_x', 'Tenure Months', 'Phone Service_x',
       'Multiple Lines_x', 'Internet Service_x', 'Online Security_x',
       'Online Backup_x', 'Device Protection', 'Tech Support',
       'Streaming TV_x', 'Streaming Movies_x', 'Contract_x',
       'Paperless Billing_x', 'Payment Method_x', 'Monthly Charges',
       'Total Charges_x', 'Churn Label', 'Churn Value', 'Churn Score', 'CLTV',
       'Churn Reason', 'Count_y', 'Quarter', 'Referred a Friend',
       'Number of Referrals', 'Tenure in Months', 'Offer', 'Phone Service_y',
       'Avg Monthly Long Distance Charges', 'Multiple Lines_y',
       'Internet Service_y', 'Internet Type', 'Avg Monthly GB Download',
       'Online Security_y', 'Online Backup_y', 'Device Protection Plan',
       'Premium Tech Support', 'Streaming TV_y', 'Streaming Movies_y',
       'Streaming Music', 'Unlimited Data', 'Contract_y',
       'Paperless Billing_y', 'Payment Method_y', 'Monthly Charge',
       'Total Charges_y', 'Total Refunds', 'Total Extra Data Charges',
       'Total Long Distance Charges', 'Total Revenue', 'Customer ID', 'Count',
       'Gender_y', 'Age', 'Under 30', 'Senior Citizen_y', 'Married',
       'Dependents_y', 'Number of Dependents'],
      dtype='object')

In [37]:
def display_all(df):
    with pd.option_context("display.max_rows", 1000, "display.max_columns", 1000): 
        display(df)

In [39]:
display_all(df.head().T)

,0,1,2,3,4
CustomerID,3668-QPYBK,9237-HQITU,9305-CDSKC,7892-POOKP,0280-XJGEX
Count_x,1,1,1,1,1
Country,United States,United States,United States,United States,United States
State,California,California,California,California,California
City,Los Angeles,Los Angeles,Los Angeles,Los Angeles,Los Angeles
Zip Code,90003,90005,90006,90010,90015
Lat Long,"33.964131, -118.272783","34.059281, -118.30742","34.048013, -118.293953","34.062125, -118.315709","34.039224, -118.266293"
Latitude,33.964131,34.059281,34.048013,34.062125,34.039224
Longitude,-118.272783,-118.30742,-118.293953,-118.315709,-118.266293
Gender_x,Male,Female,Female,Female,Male
Senior Citizen_x,No,No,No,No,No
Partner,No,No,No,Yes,No
Dependents_x,No,Yes,Yes,Yes,Yes
Tenure Months,2,2,8,28,49
Phone Service_x,Yes,Yes,Yes,Yes,Yes
Multiple Lines_x,No,No,Yes,Yes,Yes
Internet Service_x,DSL,Fiber optic,Fiber optic,Fiber optic,Fiber optic
Online Security_x,Yes,No,No,No,No
Online Backup_x,Yes,No,No,No,Yes
Device Protection,No,No,Yes,Yes,Yes
Tech Support,No,No,No,Yes,No
Streaming TV_x,No,No,Yes,Yes,Yes
Streaming Movies_x,No,No,Yes,Yes,Yes
Contract_x,Month-to-month,Month-to-month,Month-to-month,Month-to-month,Month-to-month
Paperless Billing_x,Yes,Yes,Yes,Yes,Yes
Payment Method_x,Mailed check,Electronic check,Electronic check,Electronic check,Bank transfer (automatic)
Monthly Charges,53.85,70.7,99.65,104.8,103.7
Total Charges_x,108.15,151.65,820.5,3046.05,5036.3
Churn Label,Yes,Yes,Yes,Yes,Yes
Churn Value,1,1,1,1,1
Churn Score,86,67,86,84,89
CLTV,3239,2701,5372,5003,5340
Churn Reason,Competitor made better offer,Moved,Moved,Moved,Competitor had better devices
Count_y,1,1,1,1,1
Quarter,Q3,Q3,Q3,Q3,Q3
Referred a Friend,No,No,No,No,No
Number of Referrals,0,0,0,0,0
Tenure in Months,2,2,8,28,49
Offer,None,None,None,Offer C,None
Phone Service_y,Yes,Yes,Yes,Yes,Yes
Avg Monthly Long Distance Charges,10.47,9.12,12.15,4.89,44.33
Multiple Lines_y,No,No,Yes,Yes,Yes
Internet Service_y,Yes,Yes,Yes,Yes,Yes
Internet Type,DSL,Fiber Optic,Cable,Fiber Optic,Fiber Optic
Avg Monthly GB Download,21,51,26,47,11
Online Security_y,Yes,No,No,No,No
Online Backup_y,Yes,No,No,No,Yes
Device Protection Plan,No,No,Yes,Yes,Yes
Premium Tech Support,No,No,No,Yes,No
Streaming TV_y,No,No,Yes,Yes,Yes
Streaming Movies_y,No,No,Yes,Yes,Yes
Streaming Music,No,No,Yes,Yes,Yes
Unlimited Data,Yes,Yes,Yes,Yes,Yes
Contract_y,Month-to-Month,Month-to-Month,Month-to-Month,Month-to-Month,Month-to-Month
Paperless Billing_y,Yes,Yes,Yes,Yes,Yes
Payment Method_y,Credit Card,Bank Withdrawal,Bank Withdrawal,Bank Withdrawal,Bank Withdrawal
Monthly Charge,53.85,70.7,99.65,104.8,103.7
Total Charges_y,108.15,151.65,820.5,3046.05,5036.3
Total Refunds,0.0,0.0,0.0,0.0,0.0
Total Extra Data Charges,0,0,0,0,0
Total Long Distance Charges,20.94,18.24,97.2,136.92,2172.17
Total Revenue,129.09,169.89,917.7,3182.97,7208.47
Customer ID,3668-QPYBK,9237-HQITU,9305-CDSKC,7892-POOKP,0280-XJGEX
Count,1,1,1,1,1
Gender_y,Male,Female,Female,Female,Male
Age,37,19,31,23,38
Under 30,No,Yes,No,Yes,No
Senior Citizen_y,No,No,No,No,No
Married,No,No,No,Yes,No
Dependents_y,No,Yes,Yes,Yes,Yes
Number of Dependents,0,2,2,3,1

In [43]:
# Target variable: predict the CLTV of the customer so that the company can focus on the most valuable customers 

df["CLTV"].value_counts()

5546    8
4741    7
5527    7
5092    7
4745    7
       ..
2364    1
3003    1
5280    1
3269    1
5553    1
Name: CLTV, Length: 3438, dtype: int64